### ISSUE TITLE
AddressSanitizer throws error in sqlite3_step

### ISSUE THREAD

**Issue by suburbski** [etjump/etjump#736]
Usually happens after a few ingame frames with a new profile
```
=================================================================
==234689==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fca332ac610 at pc 0x7fcac40ff3a7 bp 0x7fca332abc30 sp 0x7fca332ab3d8
READ of size 6 at 0x7fca332ac610 thread T6
    #0 0x7fcac40ff3a6 in __interceptor_memcpy ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:827
    #1 0x7fca4d7ceb21 in memcpy /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34
    #2 0x7fca4d7ceb21 in sqlite3VdbeSerialPut ../deps/sqlite/sqlite3.c:82732
    #3 0x7fca4d9d8abb in sqlite3VdbeExec ../deps/sqlite/sqlite3.c:89705
    #4 0x7fca4d9f7ad1 in sqlite3Step ../deps/sqlite/sqlite3.c:84861
    #5 0x7fca4d9f8260 in sqlite3_step ../deps/sqlite/sqlite3.c:84918
    #6 0x7fca4e02662d in AsyncOperation::ExecuteStatement() ../src/game/etj_async_operation.cpp:111
    #7 0x7fca4e104acb in Database::SaveNameOperation::Execute() ../src/game/etj_database.cpp:1464
    #8 0x7fca4e025af0 in AsyncOperation::StartThread(void*) ../src/game/etj_async_operation.cpp:32
    #9 0x7fca4e029a96 in void* std::__invoke_impl<void*, void* (*)(void*), AsyncOperation*>(std::__invoke_other, void* (*&&)(void*), AsyncOperation*&&) /usr/include/c++/11/bits/invoke.h:61
    #10 0x7fca4e029a96 in std::__invoke_result<void* (*)(void*), AsyncOperation*>::type std::__invoke<void* (*)(void*), AsyncOperation*>(void* (*&&)(void*), AsyncOperation*&&) /usr/include/c++/11/bits/invoke.h:96
    #11 0x7fca4e029a96 in void* std::thread::_Invoker<std::tuple<void* (*)(void*), AsyncOperation*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/include/c++/11/bits/std_thread.h:253
    #12 0x7fca4e029a96 in std::thread::_Invoker<std::tuple<void* (*)(void*), AsyncOperation*> >::operator()() /usr/include/c++/11/bits/std_thread.h:260
    #13 0x7fca4e029a96 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void* (*)(void*), AsyncOperation*> > >::_M_run() /usr/include/c++/11/bits/std_thread.h:211
    #14 0x7fcac27796b3  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda6b3)
    #15 0x7fcac3f56608 in start_thread /build/glibc-YbNSs7/glibc-2.31/nptl/pthread_create.c:477
    #16 0x7fcac3161292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)

Address 0x7fca332ac610 is located in stack of thread T6 at offset 304 in frame
    #0 0x7fca4e10415f in Database::SaveNameOperation::Execute() ../src/game/etj_database.cpp:1440

  This frame has 9 object(s):
    [32, 33) '<unknown>'
    [48, 49) '<unknown>'
    [64, 65) '<unknown>'
    [80, 81) '<unknown>'
    [96, 128) 'op' (line 1441)
    [160, 192) '<unknown>'
    [224, 256) '<unknown>'
    [288, 320) '<unknown>' <== Memory access at offset 304 is inside this variable
    [352, 1376) 'sanitizedName' (line 1453)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T6 created by T0 here:
    #0 0x7fcac411d6d5 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x7fcac2779989 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda989)
    #2 0x6080000b0d9f  (<unknown module>)
    #3 0x7fca4e1546df in Database::NewName(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/game/etj_database.cpp:449

SUMMARY: AddressSanitizer: stack-use-after-scope ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:827 in __interceptor_memcpy
Shadow bytes around the buggy address:
  0x0ff9c664d870: f2 f2 00 00 00 00 00 00 00 f3 f3 f3 f3 f3 00 00
  0x0ff9c664d880: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff9c664d890: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
  0x0ff9c664d8a0: f8 f2 f8 f2 f8 f2 f8 f2 00 00 00 00 f2 f2 f2 f2
  0x0ff9c664d8b0: f8 f8 f8 f8 f2 f2 f2 f2 f8 f8 f8 f8 f2 f2 f2 f2
=>0x0ff9c664d8c0: f8 f8[f8]f8 f2 f2 f2 f2 00 00 00 00 00 00 00 00
  0x0ff9c664d8d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff9c664d8e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff9c664d8f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff9c664d900: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff9c664d910: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==234689==ABORTING
```

**Comment by suburbski** [comment]
This is likely a data race
